### ISSUE TITLE
마스토돈에도 봇 계정을 만들어주셨으면 합니다.

### ISSUE THREAD

**Issue by malkoG** [overworks/aladin-newbook-notifier#3]
마스토돈은 ActivityPub 프로토콜 기반의 탈중앙화 SNS 입니다. 대부분의 기능이 트위터와 유사하며, 트위터 사용자와 마스토돈 사용자의 유저풀도 겹치는 편입니다.

• Context 1 : 최근 트위터 인수 이후, 트위터에서 마스토돈으로 이주하는 인원이 급증했습니다. https://m.slashdot.org/story/406699 
• Context 2 : 트위터 인수 이후, 봇을 비활성화시키겠다는 언급이 있었는데 이런 좋은 취지의 봇도 비활성화되지 않을까 하는 우려가 있습니다. https://twitter.com/elonmusk/status/1591334141140045824?t=TWa4GqrE7-RbsoXzcj7maA&s=19

위와 같은 이유로 마스토돈 인스턴스에도 봇을 만드는걸 고려해주시면 감사하겠습니다.

**Comment by overworks** [comment]
건의 주신 것에 감사드립니다. 저도 헤비 트잉여인지라 상황은 대충 파악하고 있습니다. 마스토돈은 초창기에 컨셉이 재미있어서 좀 기웃거리다가 다시 트위터로 돌아왔었는데, 이런 식으로 다시 주목을 받을 거라고는 생각 못했네요.

결론부터 말씀드리자면, 근시일 내에 마스토돈용 봇을 만드는 일은 아마 없지 않을까 합니다.

첫번째로 제가 일단 마스토돈을 사용할 생각이 (아직은) 없습니다. 저의 경우 트위터를 이용하는 것은 사회적 연결도 있지만, 큰 이유 중 하나가 공식계정 팔로잉을 통한 빠른 뉴스 전달입니다. 그런 면에서 마스토돈은 많이 부족하며, 주제별로 서버가 나뉘어져 있다는 특성 때문에 기업 입장에서도 진입하기 어려울거라 생각하고요.

또 다른 이유는 제 자신이 봇을 거의 이용하지 않게 되었다는 것입니다. 만화나 소설을 구매해서 읽는 빈도가 크게 줄었으며, 컴퓨터 관련 서적은 더이상 방에 공간이 없어서(...) 책을 구매하는 일이 거의 사라졌습니다. 정 필요하면 전자책을 구매하거나 도서관을 이용하게 되었습니다.

덧붙여서 알라딘도 점점 더 제휴자에게 안좋은 방향으로 조건을 변경하더니 얼마전에는 일방적으로 종료했는데, 아직은 API가 유지되긴 합니다만 이쪽도 계속될거라는 확신을 잃은 상태입니다. 이쪽은 설령 중지되더라도 대체할 수단은 많긴 합니다만...

이상의 이유로 이 이슈는 처리하지 않고 닫도록 하겠습니다. 언젠가 제가 마스토돈에 이주해서 작업을 하게 되어 다시 이 이슈를 열 수 있게 되면 좋겠습니다.
